name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This means the workflow runs whenever code is pushed to 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload everything in the repository

      - name: Deploy
        uses: actions/deploy-pages@v2
